### PR TITLE
Allow margins to get set before Show() is called.

### PR DESCRIPTION
**Pull request by EmmanVazz**
This should solve the app crashing when you set the margin parameters.

### CODE REVIEW

**Comment by MarcBruins** [comment]
Thanks a lot! Could you however use C# 6 null check? Like so: leftMarginConstraint?.value = value

**Comment by EmmanVazz** [comment]
Oh that is a neat trick, I will make that change.

**Comment by EmmanVazz** [comment]
Hmm doesn't seem like you can use it like that. 

I get a "the left-hand side of an assignment must be a variable property or indexer" compiler error. 

Mentioned here as well
http://stackoverflow.com/questions/35887106/using-the-null-conditional-operator-on-the-left-hand-side-of-an-assignment

**Comment by MarcBruins** [comment]
You are right, i'm sorry! Will merge this. Thanks!

**Pull request merged**
